### ISSUE TITLE
undefined 'require_relative'

### ISSUE THREAD

**Issue by otheus** [phemmer/ruby-corosync#1]
```
$ ruby -I /usr/lib/ruby/gems/1.8/gems/corosync-0.2.0.0/lib:/usr/lib/ruby/gems/1.8/gems/ffi-1.9.8/lib keys.rb
/usr/lib/ruby/gems/1.8/gems/corosync-0.2.0.0/lib/corosync.rb:4: undefined method `require_relative' for main:Object (NoMethodError)
        from /usr/lib/ruby/gems/1.8/gems/corosync-0.2.0.0/lib/corosync/cmap.rb:1:in `require'
        from /usr/lib/ruby/gems/1.8/gems/corosync-0.2.0.0/lib/corosync/cmap.rb:1
        from keys.rb:1:in `require'
        from keys.rb:1
$ ruby --version
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
```

**Comment by otheus** [comment]
Let me guess: I need Ruby 2.0?

**Comment by phemmer** [comment]
`require_relative` was introduced in ruby 1.9.3. However I just pushed [a commit](https://github.com/phemmer/ruby-corosync/commit/1966295fec8604ebbfab423ae58546cdc4071cd6) modifying the `.gemspec` to require ruby-2.0. This was done because CPG is severely limited on older ruby versions.
In theory though you should be able to use the gem on ruby 1.9.3 as long as you make sure not to use CPG on any thread other than the main thread.

**Comment by otheus** [comment]
Thanks
